spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: kiosk1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: GraduProject11@gmail.com
    password: rmfkeb1216!@#
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100
          dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

jwt:
  secret: jwtsecretkey

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

server:
  port: 8040
  servlet:
    session:
      tracking-modes: COOKIE
